---
label: Site Settings
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  default: Navillus
- name: url
  type: text
  config:
    required: true
  label: URL
  default: https://navillus.dev
  hidden: false
- name: author
  type: text
  config:
    required: true
  label: Author
  default: Navillus
- name: twitter_handle
  type: text
  config:
    required: true
  label: Twitter Handle
  default: navillus_dev
- name: twitter_card
  type: select
  default: summary_large_image
  config:
    required: true
    options:
    - app
    - player
    - summary
    - summary_large_image
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Twitter Card
pages:
- src/data/site.json
